[metadata]
title = "ex_dict"
description = "Example Dictionary"
version = "1.2.3"
authors = [
    "Mickey Mouse (mickey@example.com)",
    "Donald Duck (github.com/donald_duck)",
]

[config]
encoding = "UTF-8"
additional_word_characters = "'"
try_characters = "esianrtolcdugmphbyfvkwzESIANRTOLCDUGMPHBYFVKWZ'"
input_conversion = [{remove = "’", add = "'"}]
complex_prefixes = true

[prefix.non]
cross_product = true
rules = [{add = "non"}]

[prefix.re]
cross_product = true
rules = [{add = "re", stack = ["non"]}]

[suffix."'s"]
rules = [{add = "'s"}]

[suffix.ive]
cross_product = true
rules = [
    {strip = "e", add = "ive", cond = "e"},
    {add = "ive", cond = "[^e]"},
]

[[replace]]
remove = "ie"
add = "ai"

[[replace]]
remove = "alot"
add = "a lot"

[[entry]]
stem = "Sam"
keep_case = true
suffix = ["'s"]

[[entry]]
stem = "act"
prefix = ["non", "re"]
suffix = ["ive"]

[[entry]]
stem = "dismiss"
no_suggest = true
suffix = ["ive"]


# This is will generate the following files in the conventional Hunspell format
# (with possibly different flag labels):
#
#
# ex_dict.aff
# -----------
# SET UTF-8
# WORDCHARS '
# TRY esianrtolcdugmphbyfvkwzESIANRTOLCDUGMPHBYFVKWZ'
# ICONV 1
# ICONV ’ '
# NOSUGGEST !
# KEEPCASE $
# COMPLEXPREFIXES
#
# PFX A Y 1
# PFX A   0     non        .
#
# PFX A Y 1
# PFX A   0     re/N       .
#
# SFX V Y 2
# SFX V   e     ive        e
# SFX V   0     ive        [^e]
#
# SFX M N 1
# SFX M   0     's         .
#
# REP 2
# REP ie ai
# REP alot a_lot
#
#
# ex_dict.dic
# -----------
# 3
# Sam/$M
# act/AV
# dismiss/!V
#
