[metadata]
title = "ex_dict"
description = "Example Dictionary"
version = "1.2.3"
authors = [
    "Mickey Mouse (mickey@example.com)",
    "Donald Duck (github.com/donald_duck)",
]

[config]
encoding = "UTF-8"

[prefix.baz]
rules = [{add = "baz"}]

[prefix.foo]
cross_product = false
rules = [
    {add = "foo", strip = "c", cond = "c"},
    {add = "foobar", cond = "[^c]"}
]

[suffix.y]
rules = [{add = "y", stack = ["ly"]}]

[suffix.ly]
rules = [
    {add = "ly", cond = "[^y]"},
    {add = "ily", strip = "y", cond = "y"}
]

[[entry]]
stem = "Rust"
prefix = ["baz", "foo"]
suffix = ["y"]
keep_case = true

[[entry]]
stem = "crustacean"
prefix = ["baz", "foo"]
need_affix = true