[metadata]
title = "ex_dict"
description = "Example Dictionary"
version = "1.2.3"
authors = [
    "Mickey Mouse (mickey@example.com)",
    "Donald Duck (github.com/donald_duck)",
]

[config]
encoding = "UTF-8"
additional_word_characters = "'üß"
try_characters = "esianrtolcdugmphbyfvkwzESIANRTOLCDUGMPHBYFVKWZ'"
key_characters = ["qwertyuiop", "asdfghjkl", "zxcvbnm"]
map_characters = [
    {remove = "u", add = "ü"},
    {remove = "ss", add = "ß"}
]
complex_prefixes = true
input_conversion = [{remove = "’", add = "'"}]
replace = [
    {remove = "ie", add = "ei"},
    {remove = "alot", add = "a lot"},
]

[prefix.non]
rules = [{add = "non"}]

[prefix.re]
rules = [{add = "re", stack = ["non"]}]

[suffix."'s"]
cross_product = false
rules = [{add = "'s"}]

[suffix.ive]
rules = [
    {strip = "e", add = "ive", cond = "e"},
    {add = "ive", cond = "[^e]"},
]

[[entry]]
stem = "Frühstück"
keep_case = true
suffix = ["'s"]

[[entry]]
stem = "act"
prefix = ["non", "re"]
suffix = ["ive"]

[[entry]]
stem = "dismiss"
no_suggest = true
suffix = ["ive"]